modelname: sinc_mld
_target_: sinc.model.mld.MLD

latent_dim: 256
vae: true

transforms: ${transforms}

ff_size: 1024
num_layers: 6
num_head: ${model.num_layers}
droupout: 0.1
activation: "gelu"
nvids_to_save: ${callback.render.nvids_to_save}
lr_scheduler: steplr # reduceonplateau, steplr
synthetic: ${data.synthetic}


motion_branch: true
teacher_forcing: false
separate_latents: false

# concatenating text branches or not
single_text_desc: true

defaults:
  - textencoder: text_space
  - motionencoder: actor
  - motiondecoder: actor
  - losses: sinc_joint
  - optim: adamw
  - /model/losses/function/recons@func_recons
  - /model/losses/function/recons@func_latent
  - /model/losses/function/kl@func_kl
