hydra:
  run:
    dir: .
  output_subdir: null

seed: 1234

logger_level: INFO
folder: ???
classifier_path: /is/cluster/fast/nathanasiou/logs/sinc/sinc-arxiv/temos-bs64x1-scheduler/babel-amass/
classifier_ckpt: 999

split: val
mean: false
number_of_samples: 1
fact: 1
ckpt_name: last
last_ckpt_path: ${get_last_checkpoint:${folder},${ckpt_name}}

# submission | supmat | 'all'--> pairs + single (seg/seq) | pairs | single
set: pairs 

# naive == gpt | concat | null
naive: '' # for temos-indep compositions on rotations space

jointstype: rotsd
# llocations + z axes + scaling of skeleton
# jointstype: 'smplh' # smplh /

# Composing nested config with default
defaults:
  - data: null
  - machine: null
  - trainer: null
  - sampler: all_conseq
  - /path@path
  - override hydra/job_logging: custom
  - override hydra/hydra_logging: custom
  - _self_

data:
  mode: 'inference'

machine:
  batch_size: 16
  smpl_batch_size: 128
