hydra:
  run:
    dir: experiments/${project}/${experiment}/${run_id}/${data.dataname}
  job:
    chdir: true
    env_set:
      WANDB_API_KEY: '90e13be46265667b13415a5e6d248ae91ab399fc'
      PYOPENGL_PLATFORM: 'egl'
      HYDRA_FULL_ERROR: 1

# Global configurations shared between different modules
experiment: baseline
# must be the same when you are resuming experiment
project: sinc
seed: 42
logger_level: INFO
run_id: ${generate_id:}

# For finetuning
resume: null
resume_ckpt_name: null
devices: 1

# Composing nested config with default
defaults:
  - data: babel-amass
  - model: sinc_joint_single_text
  - machine: server
  - trainer: base
  - sampler: variable_conseq # cut it
  - logger: none # wandb
  - callback: base
  - /path@path
  - override hydra/job_logging: custom
  - override hydra/hydra_logging: custom
  - _self_

data:
  transforms:
    normalization: true

transforms: ${data.transforms}
